routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('/caddy-check', 'CaddyController@check');

Auth::routes(['verify' => true]);

Route::get('/logout', 'Auth\LoginController@logout')->name('get_logout');

// OAuth-Routes
Route::get('/login/{provider}', 'OauthController@redirect')->name('login_oauth');
Route::get('/login/{provider}/callback', 'OauthController@callback')->name('login_oauth_callback');


// Main Webshop Functions
Route::get('/category/{category}', 'CategoryController@index')->name('category');
Route::get('/product/{product}', 'ProductController@index')->name('product');
Route::get('/page/{page}', 'PageController@index')->name('page');
Route::get('/page/{page}/styles.css', 'PageController@styles')->name('page.styles');

Route::get('/product/image/{filename?}', 'FileController@serveProductImage')->name('product.image')
    ->where('filename', '(.*)');

Route::get('/cart/', 'CartController@cart')->name('cart');
Route::get('/cart/{product_id}/add', 'CartController@add')
    ->name('cart.add')
    ->where(['product_id' => '[0-9]+']);

Route::get('/cart/modify/{index}/{amount}', 'CartController@modify')
    ->name('cart.modify')
    ->where(['index' => '[0-9]+', 'name' => '[0-9]+']);

Route::prefix('/order')->name('order.')->middleware('auth')->group(function() {
    Route::get('/checkout', 'OrderController@checkout')->name('checkout');
    Route::post('/checkout', 'OrderController@saveCheckout')->name('saveCheckout');
    Route::get('/switchAddress/{address_id}', 'OrderController@switchAddress')
        ->name('switchAddress')
        ->where(['address_id' => '[0-9]+']);
        Route::get('/shipping', 'OrderController@shipping')->name('shipping');
        Route::get('/shipping/{option_id}', 'OrderController@saveShipping')->name('saveShipping');
        Route::get('/confirmation', 'OrderController@confirmation')->name('confirmation');
        Route::post('/complete', 'OrderController@complete')->name('complete');
        Route::get('/success', 'OrderController@success')->name('success');
});

// Account functions
Route::prefix('/account')->name('account.')->middleware('auth')->group(function() {
    Route::get('/', 'AccountController@index')->name('index');
    Route::get('/edit/', 'AccountController@edit')->name('edit');
    Route::get('/address/{address_id}/edit/', 'AccountController@editAddress')->name('address.edit');
    Route::get('/address/add/', 'AccountController@addAddress')->name('address.add');
    Route::post('/address/add/', 'AccountController@addAddress')->name('address.saveAdd');
    Route::get('/password/', 'AccountController@password')->name('password');
    Route::post('/password/', 'AccountController@updatePassword')->name('password.update');
});

// Admin Routes
Route::namespace('Admin')
    ->middleware(['auth', 'admin'])
    ->prefix('/admin')
    ->name('admin.')
    ->group(function () {
        Route::get('/', 'IndexController@Index')->name('index');
        Route::prefix('product')->name('product.')->group(function () {
            Route::get('/add/', 'ProductController@add')->name('add');
            Route::post('/add/', 'ProductController@addSave')->name('add.save');

            Route::get('/edit/', 'ProductController@editIndex')->name('edit.index');
            Route::get('/edit/{product_id}', 'ProductController@edit')->name('edit');
            Route::post('/edit/{product_id}', 'ProductController@editSave')->name('edit.save');


            Route::prefix('images')->name('images.')->group(function () {
                Route::get('/', 'ProductController@imagesIndex')->name('index');
                Route::get('/{product_id}', 'ProductController@images')->name('show');
                Route::post('/{product_id}/upload', 'ProductController@imagesUpload')->name('upload');
                Route::get('/{product_id}/current', 'ProductController@getUploadedImages')->name('current');
                Route::get('/delete/{image_name}', 'ProductController@deleteImage')->name('delete');
            });
            Route::get('/assign/', 'ProductController@assignIndex')->name('assign.index');
            Route::get('/assign/{product_id}', 'ProductController@assign')->name('assign.show');
            Route::post('/assign/{product_id}', 'ProductController@assignSave')->name('assign.save');
        });
        Route::prefix('category')->name('category.')->group(function () {
            Route::get('/add/', 'CategoryController@add')->name('add');
            Route::post('/add/', 'CategoryController@addSave')->name('add.save');

            Route::get('/edit/', 'CategoryController@editIndex')->name('edit.index');
            Route::get('/edit/{category_id}', 'CategoryController@edit')->name('edit');
            Route::post('/edit/{category_id}', 'CategoryController@editSave')->name('edit.save');
        });
        Route::prefix('page')->name('page.')->group(function () {
            Route::get('/add/', 'PageController@add')->name('add');
            Route::post('/add/', 'PageController@addSave')->name('add.save');

            Route::get('/edit/', 'PageController@editIndex')->name('edit.index');
            Route::get('/edit/{page_id}', 'PageController@edit')->name('edit');
            Route::post('/edit/{page_id}', 'PageController@editSave')->name('edit.save');

            Route::post('/edit/content/{page_id}', 'PageController@saveEditor')->name('content.save');
            Route::get('/edit/content/{page_id}', 'PageController@loadEditor')->name('content.load');

            Route::get('/assets/', 'PageController@assets')->name('assets');
            Route::post('/assets/upload', 'PageController@uploadAssets')->name('assets.upload');
        });
    });

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['user_id', 'intent_id', 'product_data', 'shipping_data', 'user_data', 'total'];
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Classes\Stripe;
use App\Classes\Order;
use App\ShippingOption;
use App\UserAddress;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{
    public static function getCurrentAddress() {
        $addressId = request()->session()->get('order.addressId');
        if (!is_int($addressId)) {
            return Auth::user()->addresses()->first();
        }
        else {
            return UserAddress::find($addressId);
        }
    }

    public function checkout(Request $r)
    {
        if (!Auth::check()) {
            $r->session()->put('url.intended', url()->current());
            return redirect()->route('login');
        }

        $addressId = $r->session()->get('order.addressId');
        if (!is_int($addressId)) $addressId = -1;

        if ($addressId > 0) {
            $address = UserAddress::find($r->session()->get('order.addressId'));
            if ($address->user_id != Auth::id()) {
                $address = Auth::user()->addresses()->first();
                $r->session()->put('order.addressId', $address->id);
            }
        } elseif ($addressId == -1) {
            $address = Auth::user()->addresses()->first();
            if ($address) {
                $r->session()->put('order.addressId', $address->id);
            }
        } elseif ($addressId == 0) {
            $address = new UserAddress();
        }

        if (!$address) {
            $address = new UserAddress();
        }

        return view('pages.order.checkout', ['address' => $address, 'addressId' => $addressId]);
    }

    public function saveCheckout(Request $r)
    {
        $data = $r->validate([
            'firstname' => 'required|string|max:255',
            'lastname' => 'required|string|max:255',
            'company' => 'string|nullable|max:255',
            'street' => 'required|string|max:255',
            'street_no' => 'required|string|max:255',
            'city' => 'required|string|max:255',
            'postcode' => 'required|integer|digits_between:1,10',
            'country' => 'required|string|max:255',
            'address_name' => 'string|nullable|max:255'
        ]);

        $addressId = $r->session()->get('order.addressId');
        if (!is_int($addressId)) $addressId = -1;

        // If address was chosen, update the values
        if ($addressId > 0) {
            $address = UserAddress::find($r->session()->get('order.addressId'));
            if ($address->user_id == Auth::id()) {
                $address->update($data);
                $address = UserAddress::find($r->session()->get('order.addressId'));
            } else {
                $address = $this->saveAddress($data);
            }
        } else {
            $address = $this->saveAddress($data);
        }
        $r->session()->put('order.addressId', $address->id);
        return redirect()->route('order.shipping');
    }

    protected function saveAddress($data)
    {
        $data['user_id'] = Auth::id();
        if (!isset($data['address_name'])) $data['address_name'] = __('common.default');

        $address = UserAddress::create($data);
        return $address;
    }

    public function switchAddress($address_id, Request $r)
    {
        if ($address_id > 0) {
            $address = UserAddress::find($address_id);
            if ($address->user_id != Auth::id()) {
                return redirect()->back();
            }
        }

        $r->session()->put('order.addressId', intval($address_id));
        return redirect()->back();
    }

    public function shipping(Request $r)
    {
        $address = UserAddress::find(intval($r->session()->get('order.addressId')));
        $user = Auth::user();
        // Sanity-Checks
        if (!$address || $user->id != $address->user_id) {
            return redirect()->route('order.checkout');
        }

        $options = ShippingOption::get();
        return view('pages.order.shipping', ['address' => $address, 'shippingOptions' => $options]);
    }

    public function saveShipping($option_id, Request $r)
    {
        $option = ShippingOption::find($option_id);
        if (!$option) {
            return redirect()->route('order.shipping');
        }

        $r->session()->put('order.shippingId', intval($option_id));

        return redirect()->route('order.confirmation');
    }

    public function confirmation(Request $r)
    {
        $cart = CartController::getCart($r);
        if ($cart->isEmpty()) {
            return redirect()->route('cart');
        }

        $address = UserAddress::find(intval($r->session()->get('order.addressId')));
        $user = Auth::user();
        // Sanity-Checks
        if (!$address || $user->id != $address->user_id) {
            return redirect()->route('order.checkout');
        }

        $shipping = ShippingOption::find(intval($r->session()->get('order.shippingId')));
        // Sanity-Checks
        if (!$shipping) {
            return redirect()->route('order.shipping');
        }

        $total = Order::calculateTotalCost($cart, $shipping);

        $order = Order::getCurrentOrder($r, $cart);
        $intent = Stripe::instance()->getCurrentIntent($order, $r->session());

        return view('pages.order.confirmation', compact('cart', 'address', 'user', 'shipping', 'total', 'intent'));
    }

    public function complete(Request $r)
    {
        if (!$r->has('intentId'))
            return redirect()->back()->with('error', __('order.payment.validationError'));
        $intentId = $r->input('intentId');

        $order = Order::getCurrentOrder($r);
        $stripe = Stripe::instance();
        $intent = $stripe->getIntent($intentId);
        if (!$stripe->validateIntent($intent, $order)) {
            return redirect()->back()->with('error', __('order.payment.validationError'));
        }

        $order->intent_id = $intentId;
        $order->save();

        $r->session()->forget('cart.products');
        $r->session()->forget('order.intentId');

        return redirect()->route('order.success');
    }

    public function success()
    {
        return view('pages.order.success');
    }
}

resources/views/pages/order/checkout.blade.php
@extends('layouts.app')

@section('content')
<div class="uk-margin-top">
    <form class="uk-form-stacked uk-container uk-container-small" method="POST" action="{{ route('order.saveCheckout') }}">
        @csrf
        <fieldset class="uk-fieldset">
            <legend class="uk-legend">
                {{ __('order.address') }}
                @include('components.addressSwitcher', ['addAddressRoute' => route('order.switchAddress', ['address_id' => 0])])
            </legend>
            @if ($errors->any())
            <div class="uk-alert-danger" uk-alert>
                <a class="uk-alert-close" uk-close></a>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            @if($addressId == 0)
            <div class="uk-margin">
                <label class="uk-form-label" for="address_name">{{ __('order.addressName') }}</label>
                <div class="uk-form-controls">
                    <input class="uk-input uk-width-1-2" id="address_name" name="address_name" type="text" value="{{ old('name') ?? $address->name ?? '' }}">
                </div>
            </div>

            @endif
            @include('components.addressForm')
            <input type="submit" class="uk-button uk-button-primary uk-align-right" value="Continue">
        </fieldset>
    </form>
</div>
@endsection

resources/views/pages/order/confirmation.blade.php
@extends('layouts.app')

@section('content')
<div class="uk-margin-top">
    <form id="paymentForm" class="uk-form-stacked uk-container uk-container-small" method="POST" action="{{ route('order.complete') }}">
        @csrf
        <fieldset class="uk-fieldset">
            <legend class="uk-legend uk-text-secondary">
                {{ __('order.confirmation') }}
            </legend>
            @include('components.flash-messages')
            <div class="uk-margin uk-card uk-card-body uk-card-default uk-card-hover uk-card-small">
                <h3 class="uk-card-title">{{ ucfirst(trans_choice('common.product', $cart->count())) }}</h3>
                <table class="uk-table uk-table-divider">
                    <thead>
                        <tr>
                            <th>{{ trans_choice('common.product', $cart->count()) }}</th>
                            <th>{{ __('order.count') }}</th>
                            <th>{{ __('common.price') }}</th>
                            <th>{{ __('common.total') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($cart as $idx => $p)
                        <tr>
                            <td>{{ $p['product']->name }}</td>
                            <td>{{ $p['count'] }}</td>
                            <td>{{ Str::currency($p['product']->price) }}</td>
                            <td>{{ Str::currency($p['product']->price * $p['count']) }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="uk-margin uk-card uk-card-body uk-card-default uk-card-hover uk-card-small">
                <h3 class="uk-card-title">{{ $shipping->name }}</h3>
                <p>{{ $shipping->details }}</p>
                <span class="uk-text-secondary uk-margin-small">{{ Str::currency($shipping->price) }}</span>
            </div>
            <div class="uk-margin uk-card uk-card-body uk-card-default uk-card-hover uk-card-small">
                <h3 class="uk-card-title">Payment</h3>
                <form class="uk-form-stacked uk-container uk-container-small" method="POST" action="{{ route('order.confirmation') }}">
                    @csrf
                    <fieldset class="uk-fieldset">
                        <div class="uk-margin">
                            <label class="uk-form-label" for="card_number">Card No.</label>
                            <div class="uk-form-controls">
                                <div id="card_number" class="field"></div>
                            </div>
                        </div>
                        <div class="uk-margin" uk-grid>
                            <div class="uk-width-1-4">
                                <label class="uk-form-label" for="card_expiry">Expiry Date</label>
                                <div class="uk-form-controls">
                                    <div id="card_expiry" class="field"></div>
                                </div>
                            </div>

                            <div class="uk-width-1-4">
                                <label class="uk-form-label" for="card_number">CVC Code</label>
                                <div class="uk-form-controls">
                                    <div id="card_cvc" class="field"></div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
                <button id="payButton" data-secret="{{ $intent->client_secret }}" class="uk-button uk-button-primary uk-align-right uk-margin-small uk-margin-small-left">{{ __('order.complete') }}</button>
                <span class="uk-text-large uk-align-right uk-margin-small">{{Str::currency($total)}}</span>
                <div id="cardErrorsAlert" style="display: none;" class="uk-alert-danger" uk-alert>
                    <a class="uk-alert-close" uk-close></a>
                    <p id="cardErrors"></p>
                </div>

            </div>
        </fieldset>
    </form>
</div>
@endsection

@push('scripts')
<script src="https://js.stripe.com/v3/"></script>
<script>
    // Create an instance of the Stripe object
    var stripe = Stripe('{{ env("STRIPE_PUBLIC_KEY") }}');

    // Create an instance of elements
    var elements = stripe.elements();

    var style = {
        base: {
            fontWeight: 400,
            fontSize: '16px',
            lineHeight: '1.4',
            color: '#555',
        },
        invalid: {
            color: '#eb1c26',
        }
    };

    var cardElement = elements.create('cardNumber', {
        style: style
    });
    cardElement.mount('#card_number');

    var exp = elements.create('cardExpiry', {
        'style': style
    });
    exp.mount('#card_expiry');

    var cvc = elements.create('cardCvc', {
        'style': style
    });
    cvc.mount('#card_cvc');

    cardElement.on('change', function(event) {
        var displayError = $('#cardErrors');
        if (event.error) {
            displayError.text(event.error.message);
            $('#cardErrorsAlert').css('display', 'inherit');
        } else {
            displayError.text('');
            $('#cardErrorsAlert').css('display', 'none');
        }
    });

    // Get payment form element
    var form = $('#paymentForm');

    form.on('submit', function(ev) {
        if (document.getElementsByName('intentId').length > 0) {
            return true;
        } else {
            ev.preventDefault();
        }

        $('#payButton').prepend('<div uk-spinner="ratio: 0.8" class="uk-margin-right"></div>');
        $('#payButton div').prop('disabled', true);

        stripe.confirmCardPayment($('#payButton').data('secret'), {
            payment_method: {
                card: cardElement,
                billing_details: {}
            }
        }).then(function(result) {
            if (result.error) {
                $('#cardErrors').text(result.error.message);
                $('#cardErrorsAlert').css('display', 'inherit');
                $('#payButton div').remove();
                $('#payButton div').prop('disabled', false);
            } else {
                // The payment has been processed!
                if (result.paymentIntent.status === 'succeeded') {
                    var hiddenInput = document.createElement('input');
                    hiddenInput.setAttribute('type', 'hidden');
                    hiddenInput.setAttribute('name', 'intentId');
                    hiddenInput.setAttribute('value', result.paymentIntent.id);
                    form.append(hiddenInput);

                    form.submit();
                }
            }
        });
    });
</script>
@endpush

resources/views/pages/order/shipping.blade.php
@extends('layouts.app')

@section('content')
<div class="uk-margin-top">
    <form class="uk-form-stacked uk-container uk-container-small" method="POST" action="{{ route('order.saveCheckout') }}">
        @csrf
        <fieldset class="uk-fieldset">
            <legend class="uk-legend">
                {{ __('order.shipping') }}
            </legend>
            @foreach($shippingOptions as $option)
            <div class="uk-margin uk-card uk-card-body uk-card-default uk-card-hover uk-card-small">
                <h3 class="uk-card-title">{{ $option->name }}</h3>
                <p>{{ $option->details }}</p>
                <a href="{{ route('order.saveShipping', ['option_id' => $option->id]) }}" class="uk-button uk-button-primary uk-align-right uk-margin-small uk-margin-small-left">{{ __('common.choose') }}</a>
                <span class="uk-text-large uk-align-right uk-margin-small">{{ Str::currency($option->price) }}</span>
            </div>
            @endforeach
        </fieldset>
    </form>
</div>
@endsection

resources/views/pages/order/success.blade.php
@extends('layouts.app')

@section('content')
<div class="uk-margin-top">
    <h1>{{ __('order.success') }}</h1>
    <p>{{ __('order.successMessage') }}</p>
</div>
@endsection