routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('/caddy-check', 'CaddyController@check');

Auth::routes(['verify' => true]);

Route::get('/logout', 'Auth\LoginController@logout')->name('get_logout');

// OAuth-Routes
Route::get('/login/{provider}', 'OauthController@redirect')->name('login_oauth');
Route::get('/login/{provider}/callback', 'OauthController@callback')->name('login_oauth_callback');


// Main Webshop Functions
Route::get('/category/{category}', 'CategoryController@index')->name('category');
Route::get('/product/{product}', 'ProductController@index')->name('product');
Route::get('/page/{page}', 'PageController@index')->name('page');
Route::get('/page/{page}/styles.css', 'PageController@styles')->name('page.styles');

Route::get('/product/image/{filename?}', 'FileController@serveProductImage')->name('product.image')
    ->where('filename', '(.*)');

Route::get('/cart/', 'CartController@cart')->name('cart');
Route::get('/cart/{product_id}/add', 'CartController@add')
    ->name('cart.add')
    ->where(['product_id' => '[0-9]+']);

Route::get('/cart/modify/{index}/{amount}', 'CartController@modify')
    ->name('cart.modify')
    ->where(['index' => '[0-9]+', 'name' => '[0-9]+']);

Route::prefix('/order')->name('order.')->middleware('auth')->group(function() {
    Route::get('/checkout', 'OrderController@checkout')->name('checkout');
    Route::post('/checkout', 'OrderController@saveCheckout')->name('saveCheckout');
    Route::get('/switchAddress/{address_id}', 'OrderController@switchAddress')
        ->name('switchAddress')
        ->where(['address_id' => '[0-9]+']);
        Route::get('/shipping', 'OrderController@shipping')->name('shipping');
        Route::get('/shipping/{option_id}', 'OrderController@saveShipping')->name('saveShipping');
        Route::get('/confirmation', 'OrderController@confirmation')->name('confirmation');
        Route::post('/complete', 'OrderController@complete')->name('complete');
        Route::get('/success', 'OrderController@success')->name('success');
});

// Account functions
Route::prefix('/account')->name('account.')->middleware('auth')->group(function() {
    Route::get('/', 'AccountController@index')->name('index');
    Route::get('/edit/', 'AccountController@edit')->name('edit');
    Route::get('/address/{address_id}/edit/', 'AccountController@editAddress')->name('address.edit');
    Route::get('/address/add/', 'AccountController@addAddress')->name('address.add');
    Route::post('/address/add/', 'AccountController@addAddress')->name('address.saveAdd');
    Route::get('/password/', 'AccountController@password')->name('password');
    Route::post('/password/', 'AccountController@updatePassword')->name('password.update');
});

// Admin Routes
Route::namespace('Admin')
    ->middleware(['auth', 'admin'])
    ->prefix('/admin')
    ->name('admin.')
    ->group(function () {
        Route::get('/', 'IndexController@Index')->name('index');
        Route::prefix('product')->name('product.')->group(function () {
            Route::get('/add/', 'ProductController@add')->name('add');
            Route::post('/add/', 'ProductController@addSave')->name('add.save');

            Route::get('/edit/', 'ProductController@editIndex')->name('edit.index');
            Route::get('/edit/{product_id}', 'ProductController@edit')->name('edit');
            Route::post('/edit/{product_id}', 'ProductController@editSave')->name('edit.save');


            Route::prefix('images')->name('images.')->group(function () {
                Route::get('/', 'ProductController@imagesIndex')->name('index');
                Route::get('/{product_id}', 'ProductController@images')->name('show');
                Route::post('/{product_id}/upload', 'ProductController@imagesUpload')->name('upload');
                Route::get('/{product_id}/current', 'ProductController@getUploadedImages')->name('current');
                Route::get('/delete/{image_name}', 'ProductController@deleteImage')->name('delete');
            });
            Route::get('/assign/', 'ProductController@assignIndex')->name('assign.index');
            Route::get('/assign/{product_id}', 'ProductController@assign')->name('assign.show');
            Route::post('/assign/{product_id}', 'ProductController@assignSave')->name('assign.save');
        });
        Route::prefix('category')->name('category.')->group(function () {
            Route::get('/add/', 'CategoryController@add')->name('add');
            Route::post('/add/', 'CategoryController@addSave')->name('add.save');

            Route::get('/edit/', 'CategoryController@editIndex')->name('edit.index');
            Route::get('/edit/{category_id}', 'CategoryController@edit')->name('edit');
            Route::post('/edit/{category_id}', 'CategoryController@editSave')->name('edit.save');
        });
        Route::prefix('page')->name('page.')->group(function () {
            Route::get('/add/', 'PageController@add')->name('add');
            Route::post('/add/', 'PageController@addSave')->name('add.save');

            Route::get('/edit/', 'PageController@editIndex')->name('edit.index');
            Route::get('/edit/{page_id}', 'PageController@edit')->name('edit');
            Route::post('/edit/{page_id}', 'PageController@editSave')->name('edit.save');

            Route::post('/edit/content/{page_id}', 'PageController@saveEditor')->name('content.save');
            Route::get('/edit/content/{page_id}', 'PageController@loadEditor')->name('content.load');

            Route::get('/assets/', 'PageController@assets')->name('assets');
            Route::post('/assets/upload', 'PageController@uploadAssets')->name('assets.upload');
        });
    });

resources/views/pages/cart.blade.php
@extends('layouts.app')

@section('content')
<div class="uk-margin-top">
    <div class="uk-card uk-card-default uk-card-body">
        <h3 class="uk-card-title">{{ __('order.cart') }}</h3>
        <table class="uk-table uk-table-divider">
            <thead>
                <tr>
                    <th>{{ trans_choice('common.product', $cart->count()) }}</th>
                    <th>{{ __('order.count') }}</th>
                    <th>{{ __('common.price') }}</th>
                    <th>{{ __('common.total') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($cart as $idx => $p)
                <tr>
                    <td>{{ $p['product']->name }}</td>
                    <td class="uk-width-auto uk-width-1-3@l">
                        <button class="uk-icon cart-button-minus uk-visible@m" uk-icon="icon: minus" type="button"></button>
                        <input type="number" class="uk-input uk-form-width-xsmall cart-count-input" data-index="{{ $idx }}" style="text-align: center;" value="{{ $p['count'] }}">
                        <button class="uk-icon cart-button-plus uk-visible@m" uk-icon="icon: plus" type="button"></button>
                        <button class="uk-icon cart-button-delete uk-text-danger uk-margin-left" uk-icon="icon: trash" type="button"></button>
                    </td>
                    <td>{{ Str::currency($p['product']->price) }}</td>
                    <td>{{ Str::currency($p['product']->price * $p['count']) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <a href="{{ route('order.checkout') }}" class="uk-button uk-button-primary uk-align-right">{{ __('order.checkout') }}</a>
        <span class="uk-text-large uk-align-right">{{ Str::currency($total) }}</span>
    </div>
</div>
@endsection

@push('scripts')
<script>
    var updateValue = debounce(function(index, value) {
        $.get('{{ url("/cart/modify") }}/' + index + '/' + value, function() {
            window.location.reload();
        });
    }, 400);

    $('.cart-button-minus').click(function() {
        var input = $(this).parent().find('input');
        var index = input.data('index');
        var value = parseInt(input.val()) - 1;
        if (value == 0) return;
        input.val(value);
        updateValue(index, value);
    });
    $('.cart-button-plus').click(function() {
        var input = $(this).parent().find('input');
        var index = input.data('index');
        var value = parseInt(input.val()) + 1;
        input.val(value);
        updateValue(index, value);
    });

    $('.cart-count-input').change(function() {
        var index = $(this).data('index');
        var value = parseInt($(this).val());
        updateValue(index, value);
    });

    $('.cart-button-delete').click(function() {
        var index = $(this).parent().find('input').data('index');
        updateValue(index, 0);
        var row = $(this).parents('tr');
        row.remove();
    });


    function debounce(a, b, c) {
        var d;
        return function() {
            var e = this,
                f = arguments;
            clearTimeout(d), d = setTimeout(function() {
                d = null, c || a.apply(e, f)
            }, b), c && !d && a.apply(e, f)
        }
    }
</script>
@endpush

resources/views/pages/category.blade.php
@extends('layouts.app')

@section('content')
<div class="uk-child-width-1-2@s uk-margin-top" uk-grid="masonry: true">
@foreach($products as $product)
    @include('components.productCard', $product)
@endforeach
</div>
@endsection

resources/views/pages/index.blade.php
@extends('layouts.app')

@section('content')
@include('components.flash-messages')
<div class="uk-child-width-1-2@s" uk-grid="masonry: true">
@foreach($products as $product)
    @include('components.productCard', $product)
@endforeach
</div>
@endsection

resources/views/pages/page.blade.php
@extends('layouts.app')

@push('styles')
    <link rel="stylesheet" href="{{ route('page.styles', ['page' => $page->id]) }}"/>
@endpush

@section('content')
    <div id="page-content">
        {!! $page->{'gjs-html'} !!}
    </div>
@endsection

resources/views/pages/product.blade.php
@extends('layouts.app')

@push('meta')
<meta name="stripe-public-key" content="{{ env('STRIPE_PUBLIC_KEY') }}">
<script type="application/ld+json">
{!! json_encode($product->generateJsonLD()) !!}
</script>
@endpush

@push('scripts')
<script src="https://js.stripe.com/v3/"></script>
@endpush

@section('content')
<div class="uk-margin-top" uk-grid>
    <div class="uk-width-1-3@l">
        <div uk-lightbox>
            @if($product->images->first())
            <a class="uk-inline" href="{{ $product->images->first()->link }}">
                <img src="{{ $product->images->first()->link }}" alt="">
            </a>
            @endif
            <div class="uk-margin-top" uk-grid>
                @foreach($product->images as $img)
                <div class="uk-width-1-3">
                    <a class="uk-inline" href="{{ $img->link }}">
                        <img src="{{ $img->link }}" alt="">
                    </a>
                </div>
                @endforeach
            </div>
        </div>
    </div>
    <div class="uk-width-2-3@l">
        <div class="uk-card uk-card-default uk-card-body">
            <h1 class="uk-heading-divider">{{ $product->name }}</h1>
            <p class="uk-text-large">{{ $product->description }}</p>
            <div class="uk-card-footer">
                <a class="uk-button uk-button-primary uk-align-right uk-margin-remove-bottom" href="{{ route('cart.add', ['product_id' => $product->id]) }}">
                    <span uk-icon="plus" class="uk-margin-small-right"></span>
                    {{ __('order.addToCart') }}
                </a>
                <span class="uk-text-large uk-align-right">{{ Str::currency($product->price) }}</span>
            </div>
        </div>
    </div>
</div>
@endsection